name: RDesign
channels:
  - pyg
  - bioconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.9
  - pytorch=1.11.0=py3.9_cuda11.3_cudnn8.2.0_0
  - torchvision=0.12.0=py39_cu113
  - torchaudio=0.11.0=py39_cu113
  - cudatoolkit=11.3.1
  - pyg=2.0.4=py39_torch_1.11.0_cu113
  - pytorch-cluster=1.6.0=py39_torch_1.11.0_cu113
  - pytorch-scatter=2.0.9=py39_torch_1.11.0_cu113
  - pytorch-sparse=0.6.14=py39_torch_1.11.0_cu113
  - pytorch-spline-conv=1.2.1=py39_torch_1.11.0_cu113
  - rdkit=2021.09.4
  - numpy=1.22.0
  - pandas=1.3.5
  - matplotlib-base=3.5.1
  - jupyter=1.0.0
  - notebook=6.4.12
  - scikit-learn=1.0.2
  - scipy=1.8.0
  - h5py=3.6.0
  - mmseqs2=13.45111
  - pip=22.0.4
  - pip:
    - addict==2.4.0
    - biopython==1.80
    - captum==0.2.0
    - cilog==1.2.3
    - click==8.1.3
    - cloudpickle==2.0.0
    - dask==2022.6.1
    - dill==0.3.4
    - dive-into-graphs==1.0.0
    - filelock==3.4.2
    - focal-frequency-loss==0.3.0
    - fsspec==2022.5.0
    - future==0.18.2
    - fvcore==0.1.5.post20220506
    - gitdb==4.0.10
    - gitpython==3.1.30
    - h5netcdf==1.0.1
    - hydra-core==1.2.0
    - hyperopt==0.1.2
    - imageio==2.16.1
    - iopath==0.1.9
    - json-tricks==3.15.5
    - llvmlite==0.39.0
    - locket==1.0.0
    - lpips==0.1.4
    - mmengine
    - mmcv
    - mock==4.0.3
    - mpmath==1.2.1
    - mypy-extensions==0.4.3
    - netcdf4==1.6.0
    - networkx==2.6.3
    - nni==2.6.1
    - numba==0.56.0
    - omegaconf==2.2.2
    - opencv-python==4.5.5.64
    - opencv-python-headless==4.5.5.64
    - openpyxl==3.0.10
    - partd==1.2.0
    - pathtools==0.1.2
    - pillow==9.0.1
    - portalocker==2.4.0
    - prettytable==3.0.0
    - protobuf==4.21.12
    - ptflops==0.6.8
    - pycodestyle==2.8.0
    - pymongo==4.0.1
    - pyscf==1.7.6.post1
    - pythonwebhdfs==0.2.3
    - pywavelets==1.3.0
    - rdkit-pypi==2022.3.4
    - requests>=2.32.2
    - responses==0.17.0
    - schema==0.7.5
    - scikit-image==0.16.2
    - sentry-sdk==1.15.0
    - setproctitle==1.3.2
    - shap==0.41.0
    - simplejson==3.17.6
    - slicer==0.0.7
    - smmap==5.0.0
    - subword-nmt==0.3.8
    - sympy==1.10.1
    - tabulate==0.8.9
    - termcolor==1.1.0
    - threadpoolctl==3.0.0
    - timm==0.5.4
    - toml==0.10.2
    - toolz==0.11.2
    - tqdm>=4.66.3
    - typed-argument-parser==1.7.2
    - typeguard==2.13.3
    - typing-inspect==0.7.1
    - urllib3>=1.26.11
    - wandb==0.13.10
    - websockets==10.1
    - xarray==2022.3.0
    - yapf==0.32.0